"""empty message

Revision ID: 61476f4cab01
Revises: d795dec3a667
Create Date: 2018-03-04 19:29:03.116643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61476f4cab01'
down_revision = 'd795dec3a667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
